name: Saludo con variable

on:
  push:
    branches: [ main, develop ]

jobs:
  saludo:
    runs-on: ubuntu-latest
    env:
      MI_NOMBRE: "Jorge Chavez"
    steps:
      - name: Saludo en main
        if: github.ref == 'refs/heads/main'
        run: echo "Hola desde main, soy Jorge Chavez."
      - name: Saludo en develop
        if: github.ref == 'refs/heads/develop'
        run: echo "Hola desde develop, soy Jorge Chavez."
